Repository ironcore-dev/gardener-extension-provider-ironcore, pull requests merged in 2023-04, with the labels that each got.

#142 Fix `csi-driver-node` pod annotation
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Labels: bug, size/XS

#144 Update image vector
  charts/images.yaml
Labels: enhancement, size/S

#147 Add auto-merge workflow for dependabot PRs
  .github/workflows/check-codegen.yml
  .github/workflows/clean.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Makefile
  hack/check-generate.sh
Labels: size/M, chore

#149 chore: update cloud-controller-manager image tag to v0.1.3
  charts/images.yaml
Labels: size/XS, chore

#155 Revert "Bump k8s.io/apimachinery from 0.26.3 to 0.27.0"
  go.mod
  go.sum
Labels: size/S, chore

#158 feat: disable topology-aware routing in service deployment
  charts/gardener-extension-admission-onmetal/charts/runtime/templates/service.yaml
  charts/gardener-extension-admission-onmetal/values.yaml
Labels: enhancement, size/XS

#159 feat: add api reference doc generation
  Makefile
  hack/api-reference/api.json
  hack/api-reference/api.md
  hack/api-reference/config.json
  hack/api-reference/template/members.tpl
  hack/api-reference/template/pkg.tpl
  hack/api-reference/template/tools.go
  hack/api-reference/template/type.tpl
Labels: documentation, enhancement, size/XL

#167 Refactor `GetOnmetalClientAndNamespaceFromCloudProviderSecret` to use `Shoot` namespace
  Makefile
  hack/api-reference/template/tools.go
  pkg/controller/infrastructure/actuator_delete.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/controller/infrastructure/configvalidator.go
  pkg/onmetal/clientutils.go
Labels: enhancement, controllers, size/S

#170 Cleanup extension provider helm chart
  Makefile
  charts/gardener-extension-provider-onmetal/templates/configmap.yaml
  charts/gardener-extension-provider-onmetal/values.yaml
  example/controller-registration.yaml
Labels: size/S, chore
