Repository ironcore-dev/gardener-extension-provider-ironcore, pull requests merged in 2023-05, with the labels that each got.

#176 Prepare v0.1.6 release and bump CCM, CSI and MCM
  VERSION
  charts/images.yaml
  example/controller-registration.yaml
Labels: size/S, chore

#173 Add bastion host controller
  Makefile
  charts/gardener-extension-provider-onmetal/doc.go
  charts/gardener-extension-provider-onmetal/templates/configmap.yaml
  charts/gardener-extension-provider-onmetal/values.yaml
  cmd/gardener-extension-provider-onmetal/app/app.go
  example/controller-registration.yaml
  go.mod
  go.sum
  hack/api-reference/config.md
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/cmd/options.go
  pkg/controller/bastion/actuator.go
  pkg/controller/bastion/actuator_delete.go
  pkg/controller/bastion/actuator_delete_test.go
  pkg/controller/bastion/actuator_reconcile.go
  pkg/controller/bastion/actuator_reconcile_test.go
  pkg/controller/bastion/add.go
  pkg/controller/bastion/configvalidator.go
  pkg/controller/bastion/configvalidator_test.go
  pkg/controller/bastion/ignition/config.go
  pkg/controller/bastion/ignition/template.yaml
  pkg/controller/bastion/options.go
  pkg/controller/bastion/suite_test.go
  pkg/controller/bastion/utils.go
  pkg/onmetal/clientutils.go
Labels: documentation, enhancement, controllers, size/XXL

#193 Add support for internal load balancer configuration for CCM
  charts/internal/cloud-provider-config/templates/cloud-provider-config.yaml
  charts/internal/cloud-provider-config/values.yaml
  docs/usage-as-end-user.md
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: documentation, enhancement, controllers, size/S
