Repository ironcore-dev/gardener-extension-provider-ironcore, pull requests merged in 2023-07, with the labels that each got.

#230 Bump `CCM`, `CSI` and `MCM` to v0.1.5
  VERSION
  charts/images.yaml
  example/controller-registration.yaml
Labels: enhancement, size/S

#234 Add `configure-cloud-routes` flag and related values and functions
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: enhancement, controllers, size/M

#237 Fix wrong cluster networking overlay detection
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: bug, controllers, size/XS

#235 Add bastion host network policy implementation
  pkg/controller/bastion/actuator_delete_test.go
  pkg/controller/bastion/actuator_reconcile.go
  pkg/controller/bastion/actuator_reconcile_test.go
  pkg/controller/bastion/options.go
Labels: enhancement, controllers, size/L

#229 Add BackupBucket and BackupEntry controllers
  Makefile
  charts/gardener-extension-provider-onmetal/doc.go
  charts/gardener-extension-provider-onmetal/templates/deployment.yaml
  charts/gardener-extension-provider-onmetal/templates/rbac.yaml
  charts/gardener-extension-provider-onmetal/values.yaml
  cmd/gardener-extension-provider-onmetal/app/app.go
  example/30-backupbucket.yaml
  example/30-backupentry.yaml
  example/controller-registration.yaml
  go.mod
  go.sum
  hack/api-reference/config.md
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/cmd/options.go
  pkg/controller/backupbucket/actuator.go
  pkg/controller/backupbucket/actuator_test.go
  pkg/controller/backupbucket/add.go
  pkg/controller/backupbucket/backupbucket.go
  pkg/controller/backupbucket/suite_test.go
  pkg/controller/backupentry/actuator.go
  pkg/controller/backupentry/actuator_test.go
  pkg/controller/backupentry/add.go
  pkg/controller/backupentry/backupentry.go
  pkg/controller/backupentry/mock_backupentry.go
  pkg/controller/backupentry/suite_test.go
  pkg/onmetal/clientutils.go
  pkg/onmetal/types.go
Labels: documentation, enhancement, controllers, size/XXL

#249 Bump `gardener` to `v1.75.x`
  cmd/gardener-extension-provider-onmetal/app/app.go
  go.mod
  go.sum
  pkg/admission/validator/secretbinding_test.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/webhook.go
  pkg/apis/onmetal/validation/controlplane_test.go
  pkg/cmd/options.go
  pkg/controller/backupbucket/actuator.go
  pkg/controller/backupbucket/add.go
  pkg/controller/backupbucket/backupbucket.go
  pkg/controller/backupbucket/suite_test.go
  pkg/controller/backupentry/actuator.go
  pkg/controller/backupentry/actuator_test.go
  pkg/controller/backupentry/add.go
  pkg/controller/backupentry/suite_test.go
  pkg/controller/bastion/actuator.go
  pkg/controller/bastion/actuator_delete.go
  pkg/controller/bastion/actuator_reconcile.go
  pkg/controller/bastion/add.go
  pkg/controller/bastion/configvalidator.go
  pkg/controller/controlplane/add.go
  pkg/controller/controlplane/suite_test.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/healthcheck/add.go
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/actuator_delete.go
  pkg/controller/infrastructure/actuator_delete_test.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/controller/infrastructure/add.go
  pkg/controller/infrastructure/configvalidator.go
  pkg/controller/infrastructure/suite_test.go
  pkg/controller/worker/actuator.go
  pkg/controller/worker/add.go
  pkg/controller/worker/machine_controller_manager.go
  pkg/controller/worker/machine_images.go
  pkg/controller/worker/machine_images_test.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
  pkg/webhook/cloudprovider/add.go
  pkg/webhook/controlplane/add.go
Labels: enhancement, controllers, size/L
