Repository ironcore-dev/gardener-extension-provider-ironcore, pull requests merged in 2023-06, with the labels that each got.

#200 Update `onmetal-api` version in go.mod file
  go.mod
  go.sum
Labels: size/XS, chore

#205 Fix `Bastion` host controller setup
  charts/gardener-extension-provider-onmetal/templates/deployment.yaml
  charts/gardener-extension-provider-onmetal/templates/rbac.yaml
  charts/gardener-extension-provider-onmetal/values.yaml
  example/00-componentconfig.yaml
  example/30-bastion.yaml
  example/controller-registration.yaml
Labels: bug, size/S

#189 Volume expansion support
  charts/images.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-storageclasses/templates/storageclasses.yaml
  charts/internal/shoot-storageclasses/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/role-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-resizer.yaml
  pkg/controller/controlplane/constants.go
  pkg/controller/controlplane/suite_test.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/onmetal/types.go
Labels: documentation, controllers, size/L

#209 Refactor test setup and use `SpecContext`
  pkg/controller/bastion/actuator_delete_test.go
  pkg/controller/bastion/actuator_reconcile_test.go
  pkg/controller/bastion/configvalidator_test.go
  pkg/controller/bastion/suite_test.go
  pkg/controller/controlplane/suite_test.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/infrastructure/actuator_delete_test.go
  pkg/controller/infrastructure/actuator_reconcile_test.go
  pkg/controller/infrastructure/configvalidator_test.go
  pkg/controller/infrastructure/suite_test.go
  pkg/controller/worker/machine_images_test.go
  pkg/controller/worker/machines_test.go
  pkg/controller/worker/suite_test.go
Labels: enhancement, controllers, size/L

#210 Fix wrong client in `Bastion` host reconciler
  pkg/controller/bastion/actuator_reconcile.go
Labels: bug, controllers, size/XS

#212 Add explicit root disk to `Bastion` host `Machine`
  charts/gardener-extension-provider-onmetal/templates/configmap.yaml
  charts/gardener-extension-provider-onmetal/values.yaml
  example/controller-registration.yaml
  hack/api-reference/config.md
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/bastion/actuator_reconcile.go
  pkg/controller/bastion/actuator_reconcile_test.go
  pkg/controller/bastion/configvalidator.go
  pkg/controller/bastion/suite_test.go
Labels: documentation, enhancement, controllers, size/L

#213 Do not base64 encode the `UserData` for `Bastion` host
  pkg/controller/bastion/actuator_reconcile.go
  pkg/controller/bastion/options.go
Labels: bug, controllers, size/XS

#218 Revendor `gardener/gardener@v1.73`
  example/20-crd-extensions.gardener.cloud_workers.yaml
  go.mod
  go.sum
  pkg/admission/validator/secret.go
  pkg/apis/onmetal/validation/shoot.go
  pkg/controller/bastion/suite_test.go
  pkg/controller/controlplane/suite_test.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/infrastructure/suite_test.go
  pkg/webhook/controlplane/add.go
Labels: enhancement, controllers, size/M

#222 Add missing `deployments/scale` resource in provider RBAC
  charts/gardener-extension-provider-onmetal/templates/rbac.yaml
  example/controller-registration.yaml
Labels: bug, size/XS

#223 Update `machine-controller-manager` and `csi-provisioner`
  charts/images.yaml
Labels: size/XS, chore

#224 Update `machine-controller-manager` chart
  charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/service.yaml
Labels: enhancement, size/S
