Repository ironcore-dev/gardener-extension-provider-ironcore, pull requests merged in 2023-03, with the labels that each got.

#85 Bump MCM, CSI and CCM to v0.1.0
  charts/images.yaml
Labels: enhancement, size/XS

#86 Bump Gardener to v1.65.1 and improve CRD generation
  Makefile
  VERSION
  charts/gardener-extension-provider-onmetal/templates/deployment.yaml
  charts/images.yaml
  example/20-crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  example/20-crd-druid.gardener.cloud_etcds.yaml
  example/20-crd-extensions.gardener.cloud_backupbuckets.yaml
  example/20-crd-extensions.gardener.cloud_backupentries.yaml
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  example/20-crd-extensions.gardener.cloud_clusters.yaml
  example/20-crd-extensions.gardener.cloud_containerruntimes.yaml
  example/20-crd-extensions.gardener.cloud_controlplanes.yaml
  example/20-crd-extensions.gardener.cloud_dnsrecords.yaml
  example/20-crd-extensions.gardener.cloud_extensions.yaml
  example/20-crd-extensions.gardener.cloud_infrastructures.yaml
  example/20-crd-extensions.gardener.cloud_networks.yaml
  example/20-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  example/20-crd-extensions.gardener.cloud_workers.yaml
  example/20-crd-resources.gardener.cloud_managedresources.yaml
  example/controller-registration.yaml
  example/doc.go
  example/kustomization.yaml
  go.mod
  go.sum
  hack/generate-crds.sh
  pkg/internal/imagevector/imagevector.go
Labels: enhancement, size/XXL

#87 Update cp, infra and worker examples
  .github/workflows/publish-docker.yml
  .github/workflows/test.yml
  example/30-controlplane.yaml
  example/30-infrastructure.yaml
  example/30-worker.yaml
Labels: size/M, chore

#88 Cleanup tools and improve `Makefile`
  Makefile
  go.mod
  go.sum
  hack/tools.go
Labels: size/M, chore

#90 Bump CSI image to `sha-8c59bc6` and MCM image to `sha-1f47d20`
  charts/images.yaml
Labels: size/XS, chore

#94 Bump CSI driver image to `sha-d332110`
  charts/images.yaml
Labels: size/XS, chore

#99 Bump MCM and CSI
  charts/images.yaml
Labels: enhancement, size/XS

#100 Remove CSI controller and node driver env vars
  charts/images.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Labels: enhancement, size/S

#101 Improve Makefile check and goimports directives
  Makefile
Labels: size/S, chore

#102 Remove `csi-resizer` components
  charts/images.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/role-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-resizer.yaml
Labels: enhancement, size/L

#103 Remove unused `csi-resizer` configuration
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/onmetal/types.go
Labels: bug, controllers, size/S

#106 Add missing heartbeat controller
  pkg/cmd/options.go
Labels: bug, size/XS

#107 Fix RBAC for extension controller
  VERSION
  charts/gardener-extension-provider-onmetal/templates/rbac.yaml
  example/controller-registration.yaml
Labels: bug, size/S

#108 Fix heartbeat controller setup
  charts/gardener-extension-provider-onmetal/templates/deployment.yaml
  charts/gardener-extension-provider-onmetal/values.yaml
  cmd/gardener-extension-provider-onmetal/app/app.go
  example/controller-registration.yaml
Labels: bug, size/S

#111 Bump CSI image to `v0.1.2` and CCM image to `sha-2153499`
  charts/images.yaml
Labels: size/XS, chore

#112 Add API validation for infrastructure configuration
  pkg/apis/onmetal/validation/infrastructure.go
  pkg/apis/onmetal/validation/infrastructure_test.go
Labels: enhancement, size/M

#113 Bump CCM to `v0.1.1`
  charts/images.yaml
Labels: size/XS, chore

#115 Fix `StorageClasses` field names in `CloudProfile`
  pkg/apis/onmetal/types_cloudprofile.go
  pkg/apis/onmetal/v1alpha1/types_cloudprofile.go
  pkg/apis/onmetal/v1alpha1/zz_generated.conversion.go
  pkg/apis/onmetal/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/onmetal/validation/cloudprofile.go
  pkg/apis/onmetal/validation/cloudprofile_test.go
  pkg/apis/onmetal/zz_generated.deepcopy.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: bug, controllers, size/M

#116 Disable volume expansion in `StorageClasses` definition
  charts/internal/shoot-storageclasses/templates/storageclasses.yaml
Labels: bug, size/XS

#123 Deprecate `DeployMachineDependencies` and `CleanupMachineDependencies`
  pkg/controller/worker/machine_dependencies.go
Labels: controllers, size/XS, chore

#124 Bump golang to 1.20
  .github/workflows/clean.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test.yml
  go.mod
Labels: size/S, chore

#125 Bump CCM to `sha-aeb1003`
  charts/images.yaml
  go.mod
  go.sum
Labels: size/S, chore

#130 Bump CCM to `v0.1.2`, CSI to `v0.1.3` and MCM to `v0.1.2`
  charts/images.yaml
Labels: size/XS, chore

#131 Add component images overwrite example to extension chart values
  charts/gardener-extension-provider-onmetal/values.yaml
  example/controller-registration.yaml
Labels: documentation, enhancement, size/S

#140 Adapt `NetworkPolicys` according to recent Gardener refactorings
  charts/gardener-extension-provider-onmetal/templates/deployment.yaml
  charts/gardener-extension-provider-onmetal/templates/service.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/service.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager-svc.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller.yaml
  example/controller-registration.yaml
Labels: enhancement, size/M
