Repository ironcore-dev/gardener-extension-provider-ironcore, pull requests merged in 2024-11, with the labels that each got.

#656 Bump extension version to v0.3.5
  VERSION
  example/controller-registration.yaml
Labels: size/XS, chore

#657 Remove deprecated `pool.UserData` usage
  pkg/controller/worker/machines.go
  pkg/controller/worker/suite_test.go
Labels: bug, controllers, size/M

#643 Update gardener version to v1.102.0
  go.mod
  go.sum
Labels: enhancement, size/L
