Repository ironcore-dev/gardener-extension-provider-ironcore, pull requests merged in 2024-09, with the labels that each got.

#632 Bump MCM, CCM and CSI driver
  imagevector/images.yaml
Labels: size/XS, chore

#633 Bump `k8s.io/*` deps to v0.29.9
  .github/workflows/lint.yml
  go.mod
  go.sum
Labels: enhancement, size/M

#634 Prepare v0.3.4 release
  VERSION
  example/controller-registration.yaml
Labels: enhancement, size/XS

#605 Update to `github.com/gardener/gardener@v1.101.0`
  cmd/gardener-extension-provider-ironcore/app/app.go
  example/20-crd-extensions.gardener.cloud_backupbuckets.yaml
  example/20-crd-extensions.gardener.cloud_backupentries.yaml
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  example/20-crd-extensions.gardener.cloud_containerruntimes.yaml
  example/20-crd-extensions.gardener.cloud_controlplanes.yaml
  example/20-crd-extensions.gardener.cloud_dnsrecords.yaml
  example/20-crd-extensions.gardener.cloud_extensions.yaml
  example/20-crd-extensions.gardener.cloud_infrastructures.yaml
  example/20-crd-extensions.gardener.cloud_networks.yaml
  example/20-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  example/20-crd-extensions.gardener.cloud_workers.yaml
  go.mod
  go.sum
  hack/api-reference/api.md
  imagevector/imagevector.go
  pkg/admission/validator/shoot.go
  pkg/apis/ironcore/helper/scheme.go
  pkg/controller/backupbucket/add.go
  pkg/controller/backupentry/add.go
  pkg/controller/bastion/add.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/infrastructure/add.go
  pkg/controller/worker/add.go
  pkg/controller/worker/machine_images.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: documentation, controllers, size/L, apis
