Repository ironcore-dev/gardener-extension-provider-ironcore, pull requests merged in 2025-07, with the labels that each got.

#769 Add CloudProfile validation webhook
  pkg/admission/validator/cloudprofile.go
  pkg/admission/validator/serialization.go
  pkg/admission/validator/webhook.go
  pkg/apis/ironcore/validation/cloudprofile.go
  pkg/apis/ironcore/validation/cloudprofile_test.go
Labels: enhancement, size/L, apis, area/gardener-extension

#776 Add OCI chart releaser workflow
  .github/workflows/release-chart.yaml
  README.md
Labels: documentation, enhancement, size/M

#779 Separate Helm charts for admission runtime and application
  .github/workflows/release-chart.yaml
Labels: enhancement, size/XS

#771 Add `NamespacedCloudProfile` validation and mutation webhooks
  Makefile
  pkg/admission/cmd/options.go
  pkg/admission/mutator/namespacedcloudprofile.go
  pkg/admission/mutator/namespacedcloudprofile_test.go
  pkg/admission/mutator/webhook.go
  pkg/admission/validator/namespacedcloudprofile.go
  pkg/admission/validator/namespacedcloudprofile_test.go
  pkg/admission/validator/webhook.go
Labels: enhancement, size/XL, area/gardener-extension
