Repository ironcore-dev/gardener-extension-provider-ironcore, pull requests merged in 2025-04, with the labels that each got.

#701 Make extension ports configurable via helm values
  charts/gardener-extension-provider-ironcore/templates/deployment.yaml
  charts/gardener-extension-provider-ironcore/templates/service.yaml
  charts/gardener-extension-provider-ironcore/values.yaml
  example/controller-registration.yaml
Labels: enhancement, size/M

#716 Update container build workflow
  .github/workflows/publish-docker.yml
Labels: size/S, chore

#717 Bump `github.com/gardener/gardener` to v1.113
  .github/workflows/lint.yml
  Makefile
  cmd/gardener-extension-admission-ironcore/app/app.go
  example/20-crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  example/20-crd-druid.gardener.cloud_etcds.yaml
  example/20-crd-extensions.gardener.cloud_backupbuckets.yaml
  example/20-crd-extensions.gardener.cloud_backupentries.yaml
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  example/20-crd-extensions.gardener.cloud_clusters.yaml
  example/20-crd-extensions.gardener.cloud_containerruntimes.yaml
  example/20-crd-extensions.gardener.cloud_controlplanes.yaml
  example/20-crd-extensions.gardener.cloud_dnsrecords.yaml
  example/20-crd-extensions.gardener.cloud_extensions.yaml
  example/20-crd-extensions.gardener.cloud_infrastructures.yaml
  example/20-crd-extensions.gardener.cloud_networks.yaml
  example/20-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  example/20-crd-extensions.gardener.cloud_workers.yaml
  example/20-crd-resources.gardener.cloud_managedresources.yaml
  go.mod
  go.sum
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/ironcore/doc.go
  pkg/cmd/config.go
  pkg/controller/backupbucket/add.go
  pkg/controller/backupbucket/suite_test.go
  pkg/controller/backupentry/add.go
  pkg/controller/backupentry/suite_test.go
  pkg/controller/bastion/suite_test.go
  pkg/controller/controlplane/add.go
  pkg/controller/controlplane/suite_test.go
  pkg/controller/healthcheck/add.go
  pkg/controller/infrastructure/add.go
  pkg/controller/infrastructure/suite_test.go
  pkg/controller/worker/add.go
  pkg/controller/worker/suite_test.go
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: enhancement, ok-to-image, controllers, size/XL, apis

#719 Bump CCM, MCM and CSI
  imagevector/images.yaml
Labels: enhancement, size/XS

#728 Prepare v0.3.8 release
  VERSION
  example/controller-registration.yaml
Labels: size/XS, chore
